import { brandColors, brandGradients, brandRgb } from './brand';

const {
  white,
  ivory,
  cream,
  tan,
  gold,
  gray200,
  gray400,
  gray600,
  chocolate,
  brown,
  black,
  charcoal,
} = brandColors;
const { chocolate: ch, black: b } = brandRgb;

export const lightPalette = {
  primary: chocolate,
  primaryLight: cream,
  primaryDark: brown,
  accentBlue: gray600,
  accentPink: gray600,
  accentOrange: chocolate,
  surface: white,
  surfaceElevated: ivory,
  background: ivory,
  backgroundAlt: cream,
  text: chocolate,
  textSecondary: gray600,
  textMuted: gray400,
  success: gray600,
  warning: gray600,
  error: chocolate,
  border: tan,
  borderLight: cream,
  overlay: `rgba(${ch}, 0.45)`,
  glass: `rgba(${brandRgb.white}, 0.92)`,
  shadow: `rgba(${ch}, 0.08)`,
  shadowStrong: `rgba(${ch}, 0.14)`,
  gradientHero: brandGradients.warm,
  gradientPrimary: gold,
  gradientCard: brandGradients.card,
} as const;

export const darkPalette = {
  primary: white,
  primaryLight: charcoal,
  primaryDark: gray200,
  accentBlue: gray400,
  accentPink: gray400,
  accentOrange: white,
  surface: charcoal,
  surfaceElevated: black,
  background: black,
  backgroundAlt: charcoal,
  text: white,
  textSecondary: gray400,
  textMuted: gray600,
  success: gray400,
  warning: gray400,
  error: white,
  border: gray600,
  borderLight: charcoal,
  overlay: `rgba(${b}, 0.65)`,
  glass: `rgba(${b}, 0.85)`,
  shadow: `rgba(0, 0, 0, 0.35)`,
  shadowStrong: `rgba(0, 0, 0, 0.5)`,
  gradientHero: brandGradients.dusk,
  gradientPrimary: gold,
  gradientCard: brandGradients.cardDark,
} as const;

export type ThemePalette = typeof lightPalette | typeof darkPalette;
