import { brandColors, brandGradients, brandRgb } from './brand';

const {
  white,
  ivory,
  cream,
  tan,
  gray400,
  gray600,
  chocolate,
  brown,
  black,
  charcoal,
  pink500,
  pink400,
  pink100,
  pink50,
  accent500,
  accent100,
  ink900,
  heroBg,
  success500,
  success50,
  warning500,
  danger500,
  info500,
  info50,
} = brandColors;
const { ink: ik, black: b } = brandRgb;

export const lightPalette = {
  primary: pink500,
  primaryLight: pink100,
  primaryDark: brown,
  accentBlue: info500,
  accentPink: pink400,
  accentOrange: accent500,
  accentSoft: accent100,
  surface: white,
  surfaceElevated: ivory,
  background: ivory,
  backgroundAlt: pink50,
  backgroundTint: pink100,
  ink: ink900,
  inkElevated: charcoal,
  hero: heroBg,
  onInk: white,
  onInkMuted: 'rgba(255, 255, 255, 0.72)',
  text: chocolate,
  textSecondary: gray600,
  textMuted: gray400,
  textOnPrimary: white,
  success: success500,
  successSoft: success50,
  warning: warning500,
  error: danger500,
  info: info500,
  infoSoft: info50,
  border: tan,
  borderLight: cream,
  overlay: `rgba(${ik}, 0.55)`,
  glass: `rgba(${brandRgb.white}, 0.92)`,
  shadow: `rgba(${ik}, 0.06)`,
  shadowStrong: `rgba(${ik}, 0.12)`,
  gradientHero: brandGradients.hero,
  gradientPrimary: pink500,
  gradientCard: brandGradients.card,
} as const;

export const darkPalette = {
  primary: pink400,
  primaryLight: charcoal,
  primaryDark: pink500,
  accentBlue: info500,
  accentPink: pink400,
  accentOrange: accent500,
  accentSoft: charcoal,
  surface: charcoal,
  surfaceElevated: black,
  background: black,
  backgroundAlt: charcoal,
  backgroundTint: charcoal,
  ink: black,
  inkElevated: charcoal,
  hero: heroBg,
  onInk: white,
  onInkMuted: 'rgba(255, 255, 255, 0.72)',
  text: white,
  textSecondary: gray400,
  textMuted: gray600,
  textOnPrimary: white,
  success: success500,
  successSoft: charcoal,
  warning: warning500,
  error: danger500,
  info: info500,
  infoSoft: charcoal,
  border: gray600,
  borderLight: charcoal,
  overlay: `rgba(${b}, 0.68)`,
  glass: `rgba(${b}, 0.85)`,
  shadow: `rgba(0, 0, 0, 0.35)`,
  shadowStrong: `rgba(0, 0, 0, 0.5)`,
  gradientHero: brandGradients.hero,
  gradientPrimary: pink400,
  gradientCard: brandGradients.cardDark,
} as const;

export type ThemePalette = typeof lightPalette | typeof darkPalette;
